export { equalizer2 as filter } from 'react-icons-kit/icomoon/equalizer2';
export { plus } from 'react-icons-kit/entypo/plus';
export { minus } from 'react-icons-kit/entypo/minus';
export { x } from 'react-icons-kit/feather/x';
export { menu } from 'react-icons-kit/feather/menu';
export { shoppingCart } from 'react-icons-kit/feather/shoppingCart';
export { arrowLeft } from 'react-icons-kit/feather/arrowLeft';
export { arrowRight } from 'react-icons-kit/feather/arrowRight';
export { user } from 'react-icons-kit/feather/user';
export { phone } from 'react-icons-kit/icomoon/phone';
export { mail } from 'react-icons-kit/entypo/mail';
export { instagram } from 'react-icons-kit/fa/instagram';
export { facebook } from 'react-icons-kit/fa/facebookF';
export { youtube } from 'react-icons-kit/fa/youtube';
export { twitter } from 'react-icons-kit/fa/twitter';
export { pinterest } from 'react-icons-kit/fa/pinterest';
export { chevronRight } from 'react-icons-kit/feather/chevronRight';
export { chevronLeft } from 'react-icons-kit/feather/chevronLeft';
export { heartO as emptyHeart } from 'react-icons-kit/fa/heartO';
export { search } from 'react-icons-kit/fa/search';
export { userCheck } from 'react-icons-kit/feather/userCheck';
export { packageIcon } from 'react-icons-kit/feather/packageIcon';
export { heart } from 'react-icons-kit/feather/heart';
export { home } from 'react-icons-kit/feather/home';
export { checkSquareO } from 'react-icons-kit/fa/checkSquareO';
export { mobile } from 'react-icons-kit/fa/mobile';
export { trash } from 'react-icons-kit/fa/trash';
export { heart as FAHeart } from "react-icons-kit/fa/heart";
export { ic_navigate_next } from "react-icons-kit/md/ic_navigate_next";
export { userO } from "react-icons-kit/fa/userO";
export { info } from "react-icons-kit/feather/info";
export { userCircleO } from "react-icons-kit/fa/userCircleO";
export { paypal } from "react-icons-kit/fa/paypal";
export { money } from "react-icons-kit/fa/money";
export { bank } from "react-icons-kit/fa/bank";
export { wallet } from "react-icons-kit/entypo/wallet";
export { creditCard } from "react-icons-kit/fa/creditCard";
export { qrcode } from "react-icons-kit/fa/qrcode";
export { card } from "react-icons-kit/iconic/card";
export { checkSquare } from "react-icons-kit/fa/checkSquare";
export * from './social';
export { questionCircle } from 'react-icons-kit/fa/questionCircle';
export { ic_edit } from 'react-icons-kit/md/ic_edit';