export const HOMEPAGE_CAROUSELS_REQUEST = 'mage-pwa/homepage/HOMEPAGE_CAROUSELS_REQUEST';
export const HOMEPAGE_CAROUSELS_SUCCESS = 'mage-pwa/homepage/HOMEPAGE_CAROUSELS_SUCCESS';
export const HOMEPAGE_CAROUSELS_ERROR = 'mage-pwa/homepage/HOMEPAGE_CAROUSELS_ERROR';
