export const phoneRegex = /^((\\+[1-2]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/;
export const emailRegex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
export const nameRegex = /^[a-zA-Z][a-zA-Z ]*$/;
export const newPhoneRegex = /^[6-9]\d{9}$/;
export const cityRegex = /^[a-zA-Z- ]*$/;
export const regionRegex = /^[a-zA-Z-& ]*$/;
export const addressRegex = /^([A-Za-z0-9()$&+,:;=?@#|'"<>.-^*()%!\-\{}\`\~\s]*$)/;
export const noSpaceRegex = /^([^\s*])/;
export const pincodeRegex = /^[1-9][0-9]{5}$/;
export const nonNumberRegex = /^[0-9]/;
export const streetRegex = /[^-,/a-zA-Z0-9 ]/g;