// import getConfig from 'next/config';
// const { publicRuntimeConfig } = getConfig();
// const {
//   FBAPP_ID,
//   API_URL,
//   SERVERLESS_BASE_URL,
//   SERVERLESS_URL,
//   SITE_TITLE,
//   NODE_ENV,
//   RZP_KEY,
//   GFONT_URL,
//   CDN_URL,
//   STATIC_CDN_URL,
//   BRAND_TITLE,
//   STATIC_CDN,
//   GCLIENT_ID,
//   FILESPACE,
//   PAYPAL_CLIENT_ID,
//   NEW_LAUNCHES_CATEGORY_ID,
//   BEST_SELLER_CATEGORY_ID,
//   ENABLE_GTM,
//   SELF_URL,
//   PORT,
//   APPLICABLE_WALLET_PERCENTAGE,
//   ALGOLIA_APP,
//   ALGOLIA_KEY,
//   CLEVERTAP_KEY,
//   GTM_KEY,
//   GCM_SENDER_ID
// } = publicRuntimeConfig;

// const config = {
//   apiUrl: API_URL,
//   serverlessUrl: SERVERLESS_URL,
//   selfUrl: SELF_URL,
//   siteTitle: SITE_TITLE,
//   nodeEnv: NODE_ENV,
//   rzpKey: RZP_KEY,
//   gfontUrl: GFONT_URL,
//   cdnUrl: CDN_URL,
//   staticCdnUrl: STATIC_CDN_URL,
//   staticCdn: STATIC_CDN,
//   brandTitle: BRAND_TITLE,
//   gClientId: GCLIENT_ID,
//   fbAppId: FBAPP_ID,
//   filespace: FILESPACE,
//   paypalClientId: PAYPAL_CLIENT_ID,
//   enableGTM: ENABLE_GTM,
//   port: PORT,
//   applicableWalletPercentage: (parseInt(APPLICABLE_WALLET_PERCENTAGE)) ? parseInt(APPLICABLE_WALLET_PERCENTAGE) : 70,
//   serverlessBaseUrl: SERVERLESS_BASE_URL,
//   bestSellerCategoryId: (parseInt(BEST_SELLER_CATEGORY_ID)) ? parseInt(BEST_SELLER_CATEGORY_ID) : 98,
//   newLaunchesCategoryId: (parseInt(NEW_LAUNCHES_CATEGORY_ID)) ? parseInt(NEW_LAUNCHES_CATEGORY_ID) : 112,
//   algoliaApp: ALGOLIA_APP,
//   algoliaKey: ALGOLIA_KEY,
//   clevertapKey: CLEVERTAP_KEY,
//   gtmKey: GTM_KEY,
//   gcmSenderId: GCM_SENDER_ID
// };

// export default config;
